"""Write src/scale/REPORT.md from the saved summary, so the prose and the results stay in step."""

from __future__ import annotations

import math
from pathlib import Path

import polars as pl

import study

REPORT_PATH = Path(__file__).resolve().parent / "REPORT.md"
RISK = 0.01  # the "1% chance of any false match" budget used for capacities


def f3(x: float) -> str:
    return f"{x:.3f}"


def count(x: float) -> str:
    """A count or a capacity: grouped digits, then powers of ten once it gets astronomical."""
    if math.isinf(x):
        return "beyond float range"
    if x >= 1e9:
        return f"{x:.1e}".replace("e+", " × 10^")
    return f"{round(x):,}" if x >= 1 else f"{x:.2g}"


def chance(x: float) -> str:
    if x == 0:
        return "0"
    if x < 1e-3:
        return f"{x:.1e}".replace("e-", " × 10^-")
    return f"{x:.1%}"


def capacities(dimension: int, match: int, unrelated_share: float) -> tuple[float, float]:
    """Records that fit a 1% chance of any false match: one search, and the whole dataset.

    One search makes about N comparisons, so N p(T) <= RISK. The dataset has about N^2 / 2
    pairs, so N^2 / 2 p(T) <= RISK. Only unrelated pairs can be false matches.
    """
    p = study.tail_probability(study.threshold(match, dimension), dimension) * unrelated_share
    if p == 0:
        return math.inf, math.inf
    return RISK / p, math.sqrt(2 * RISK / p)


def write_report(summary: pl.DataFrame, data_settings: dict, timings: dict):
    unrelated_share = data_settings["pair_share_by_k"][0]
    first, last = study.DIMENSIONS[0], study.DIMENSIONS[-1]
    largest = max(study.SIZES)
    at = {(r["dimension"], r["n"]): r for r in summary.iter_rows(named=True)}
    big = at[(first, largest)]

    results = [
        (
            "| D | Records | Pairs | 1-fact threshold | Highest unrelated score (mean of trials) "
            "| Expected false pairs | Measured false pairs (mean) | Dataset with a false match: "
            "predicted / measured | One search with a false match: predicted / measured |"
        ),
        "|---:|---:|---:|---:|---:|---:|---:|---|---|",
    ]
    for r in summary.iter_rows(named=True):
        results.append(
            f"| {r['dimension']:,} | {r['n']:,} | {r['pairs']:,} | {f3(r['threshold_1'])} "
            f"| {f3(r['highest_unrelated_mean'])} | {count(r['expected_false_pairs_1'])} "
            f"| {r['false_pairs_1_mean']:.2f} "
            f"| {chance(r['dataset_chance_1'])} / {chance(r['dataset_with_false_1'])} "
            f"| {chance(r['search_chance_1'])} / {chance(r['search_with_false_1'])} |"
        )

    misses = [
        (
            "| D | 1-fact threshold | Misses among pairs sharing 1+ | 2-fact threshold "
            "| Misses among pairs sharing 2+ |"
        ),
        "|---:|---:|---:|---:|---:|",
    ]
    for d in study.DIMENSIONS:
        r = at[(d, largest)]
        misses.append(
            f"| {d:,} | {f3(r['threshold_1'])} | {r['miss_rate_1']:.3%} "
            f"| {f3(r['threshold_2'])} | {r['miss_rate_2']:.3%} |"
        )

    scale = [
        (
            "| D | Storage per hypervector | Match means | One search: records within a 1% risk "
            "| Whole dataset: records within a 1% risk |"
        ),
        "|---:|---:|---|---:|---:|",
    ]
    for d in study.DIMENSIONS:
        for q in study.MATCHES:
            search, dataset = capacities(d, q, unrelated_share)
            scale.append(
                f"| {d:,} | {d // 1024} KB | sharing {q}+ of 5 | {count(search)} | {count(dataset)} |"
            )

    two_fact_false = int(summary["false_pairs_2_mean"].sum())
    seconds = sum(v for k, v in timings.items() if k.startswith("d"))

    text = f"""# How many records fit before chance looks like a match?

Each record is a hypervector that bundles five facts. Two records that share a fact should score higher than two that share nothing, but unrelated records also score a little above or below zero by chance. This study asks how often chance alone crosses a match threshold, for the two jobs a practitioner actually does:

- **Searching for one person** compares one record with the other N − 1. Its risk grows with N.
- **Checking the whole dataset** (deduplication, clustering, building a similarity graph) compares every pair, about N²/2 of them. Its risk grows with N², so it runs out first. This is the birthday paradox: a match for *you* is rare, a match between *any two* people is common.

The [methodology](METHODOLOGY.md) gives the design; this report is regenerated by `run.py`.

## Setup

- **Records.** The first 4,000, 13,000 and 40,000 of {data_settings["record_count"]:,} synthetic records with five independent, uniformly drawn properties: region (20 values), education (10), occupation (100), interest cluster (200) and employer (1,000). {unrelated_share:.1%} of pairs share no property.
- **Encoder.** Each fact is a role hypervector bound to a value hypervector (both random ±1). A record is the raw sum of its five facts, with no sign step, so every fact can still be unbound. Stored as int8, a record hypervector takes D bytes.
- **Score.** Cosine similarity between two records.
- **Matches and thresholds.** A pair sharing q properties averages q/5. Each threshold sits 3.09 spreads below that average, T = q/5 − 3.09/√D, to keep about 99.9% of true matches.
- **Trials.** Every record is compared with every other once, with fresh hypervectors per trial: {", ".join(f"{study.TRIALS[d]} at D = {d:,}" for d in study.DIMENSIONS)}. All trials took {seconds:.0f} seconds on one laptop CPU.

## Theory in four steps

1. A pair sharing q of 5 properties scores about **q/5** on average.
2. Put the threshold at **T = q/5 − 3.09/√D**, so about 99.9% of those pairs score above it.
3. An unrelated pair crosses T by chance with probability **p(T)**, from the binomial model: count agreeing coordinates as coin flips. The model is exact for ±1 records; for raw sums it has the right average (0) and spread (1/√D).
4. Expected false matches = **comparisons × p(T)**. One search makes about N comparisons; the whole dataset makes about N²/2.

## Results: one-fact matches

{chr(10).join(results)}

At D = {first:,} and {largest:,} records, theory expects {big["expected_false_pairs_1"]:.2f} false pairs in the dataset, a {chance(big["dataset_chance_1"])} chance of at least one. The measured chance over {big["trials"]} trials is {chance(big["dataset_with_false_1"])}. The chance that one person's search returns a false match is {chance(big["search_chance_1"])} predicted and {chance(big["search_with_false_1"])} measured. At D = {study.DIMENSIONS[1]:,} and {last:,}, no false match occurred in any trial, as predicted.

With two-fact matches, {two_fact_false} false pairs occurred across every setting and trial.

## Results: missed matches

{chr(10).join(misses)}

The thresholds use 1/√D as the spread for every group. Pairs that share facts spread a little less, so the measured miss rates sit below the 0.1% target.

## What the formula says at scale

The measurements check the formula where its predictions are small enough to test. The same formula gives the record counts that keep the chance of any false match at or below {RISK:.0%}:

{chr(10).join(scale)}

These are formula outputs, not measurements. They assume independent, uniformly drawn properties and the binomial tail; skewed or correlated real data shifts them.

## Conditions and limits

The results describe five independent, uniformly distributed categorical properties, raw-sum bundling of exactly five facts, exact cosine and the binomial tail model. Real records have popular values and correlated properties, which create genuine overlaps and change how many pairs are unrelated. An application still needs its own definition of a match.

## Files

All in `results/scale/`: `trials.csv` (one row per dimension, trial and size), `summary.csv` (measured and predicted per dimension and size), `score_histograms.csv`, `figure1_scores.png/.svg`, `figure2_false_matches.png/.svg` and `manifest.json`. Regenerate everything with `sh src/scale/reproduce.sh` from the repository root.

![Score histograms](../../results/scale/figure1_scores.png)

![False matches: one search vs the whole dataset](../../results/scale/figure2_false_matches.png)
"""
    REPORT_PATH.write_text(text)
